CREATE TABLE Faqs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q VARCHAR(500) NOT NULL,
    a TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
